CREATE DATABASE IF NOT EXISTS rte;
use rte;

CREATE TABLE RTE_DATA (
    timestamp1 BIGINT NOT NULL,
    consommation INT,
    PRIMARY KEY (timestamp1)
);

DROP TABLE RTE_DATA;
DELETE FROM RTE_DATA;

LOAD IGNORE DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/RTE_data.csv'
INTO TABLE RTE_DATA 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/RTE_data.csv' IGNORE
INTO TABLE RTE_DATA 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
SELECT * FROM rte_data;

SHOW VARIABLES LIKE "secure_file_priv";

